/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg red,
    output reg green,
    output reg blue,
    output reg hsync,
    output reg vsync
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_game_red;
  wire [1-1:0] M_game_green;
  wire [1-1:0] M_game_blue;
  wire [1-1:0] M_game_hsync;
  wire [1-1:0] M_game_vsync;
  game_2 game (
    .clk(clk),
    .rst(rst),
    .red(M_game_red),
    .green(M_game_green),
    .blue(M_game_blue),
    .hsync(M_game_hsync),
    .vsync(M_game_vsync)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    red = M_game_red;
    green = M_game_green;
    blue = M_game_blue;
    hsync = M_game_hsync;
    vsync = M_game_vsync;
  end
endmodule
