/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_20 (
    input [5:0] alufn,
    input [7:0] op1,
    input [4:0] op2,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = 8'bxxxxxxxx;
    
    case (alufn)
      6'h20: begin
        out = op1 << op2;
      end
      6'h21: begin
        out = op1 >> op2;
      end
      6'h23: begin
        out = $signed(op1) >>> op2;
      end
      6'h24: begin
        out[1+6-:7] = op1[0+6-:7];
        out[0+0-:1] = op1[7+0-:1];
      end
    endcase
  end
endmodule
