/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module numbers_26 (
    input clk,
    input [3:0] n,
    input [5:0] i,
    input [4:0] j,
    output reg [2:0] pixel
  );
  
  
  
  wire [3-1:0] M_zero_pixel;
  reg [6-1:0] M_zero_i;
  reg [5-1:0] M_zero_j;
  zero_28 zero (
    .clk(clk),
    .i(M_zero_i),
    .j(M_zero_j),
    .pixel(M_zero_pixel)
  );
  wire [3-1:0] M_one_pixel;
  reg [6-1:0] M_one_i;
  reg [5-1:0] M_one_j;
  one_29 one (
    .clk(clk),
    .i(M_one_i),
    .j(M_one_j),
    .pixel(M_one_pixel)
  );
  wire [3-1:0] M_two_pixel;
  reg [6-1:0] M_two_i;
  reg [5-1:0] M_two_j;
  two_30 two (
    .clk(clk),
    .i(M_two_i),
    .j(M_two_j),
    .pixel(M_two_pixel)
  );
  wire [3-1:0] M_three_pixel;
  reg [6-1:0] M_three_i;
  reg [5-1:0] M_three_j;
  three_31 three (
    .clk(clk),
    .i(M_three_i),
    .j(M_three_j),
    .pixel(M_three_pixel)
  );
  
  always @* begin
    M_zero_i = i;
    M_zero_j = j;
    M_one_i = i;
    M_one_j = j;
    M_two_i = i;
    M_two_j = j;
    M_three_i = i;
    M_three_j = j;
    if (n == 1'h0) begin
      pixel = M_zero_pixel;
    end else begin
      if (n == 1'h1) begin
        pixel = M_one_pixel;
      end else begin
        if (n == 2'h2) begin
          pixel = M_two_pixel;
        end else begin
          if (n == 2'h3) begin
            pixel = M_three_pixel;
          end else begin
            pixel = 1'h0;
          end
        end
      end
    end
  end
endmodule
